name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    environment:
      name: testing
    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_USER: ${{secrets.DB_USER}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_PASS: ${{secrets.DB_PASS}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt 

  deploy:
    environment:
      name: testing
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} 
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-north-1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to EC2
        run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r app/src ec2-user@${{secrets.EC2_PUBLIC_IP}}:/home/ubuntu

      - name: Restart uvicorn
        run: ssh -i ~/.ssh/id_rsa ec2-user@${{secrets.EC2_PUBLIC_IP}} "cd /home/ubuntu/app/src && pkill -f uvicorn; uvicorn main:app --host 0.0.0.0 --port 80"

      - name: Start systemd service 
        run: ssh ec2-user@ec2-instance-public-ip "sudo systemctl ewstart documind"

      - name: Check service status
        run: ssh ec2-user@ec2-instance-public-ip "sudo systemctl status documind"
